from typing import BinaryIO, Protocol


class ObjectStorage(Protocol):
    def put(self, key: str, body: BinaryIO, content_type: str) -> str: ...
    def open(self, key: str) -> BinaryIO: ...
    def delete(self, key: str) -> None: ...
