"""operational_workflows"""

import sqlalchemy as sa

from alembic import op

revision = "0a3008a0d26f"
down_revision = "6fc9f43978ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_deliveries",
        sa.Column("event_key", sa.String(length=255), nullable=False),
        sa.Column("recipient_key", sa.String(length=255), nullable=False),
        sa.Column("channel", sa.String(length=30), nullable=False),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "SENT", "DELIVERED", "FAILED", "ACKNOWLEDGED", name="deliverystatus"),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
        sa.UniqueConstraint(
            "event_key", "recipient_key", "channel", name="uq_notification_deduplication"
        ),
    )
    op.create_table(
        "playbooks",
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column(
            "risk_domain",
            sa.Enum("DROUGHT", "RIVER_FLOOD", "FLASH_FLOOD", "FOOD_SECURITY", name="riskdomain"),
            nullable=False,
        ),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_playbooks_approved_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playbooks")),
        sa.UniqueConstraint("name", name=op.f("uq_playbooks_name")),
    )
    op.create_table(
        "action_plans",
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("playbook_id", sa.Uuid(), nullable=False),
        sa.Column("owner_organization_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"], ["alerts.id"], name=op.f("fk_action_plans_alert_id_alerts")
        ),
        sa.ForeignKeyConstraint(
            ["owner_organization_id"],
            ["organizations.id"],
            name=op.f("fk_action_plans_owner_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["playbook_id"], ["playbooks.id"], name=op.f("fk_action_plans_playbook_id_playbooks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_plans")),
    )
    op.create_index(op.f("ix_action_plans_alert_id"), "action_plans", ["alert_id"], unique=False)
    op.create_table(
        "exposure_assessments",
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("admin_unit_id", sa.Uuid(), nullable=False),
        sa.Column("population", sa.Float(), nullable=True),
        sa.Column("settlements", sa.Float(), nullable=True),
        sa.Column("cropland_hectares", sa.Float(), nullable=True),
        sa.Column("infrastructure", sa.JSON(), nullable=False),
        sa.Column("source_lineage", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_unit_id"],
            ["admin_units.id"],
            name=op.f("fk_exposure_assessments_admin_unit_id_admin_units"),
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"], ["alerts.id"], name=op.f("fk_exposure_assessments_alert_id_alerts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exposure_assessments")),
    )
    op.create_index(
        op.f("ix_exposure_assessments_alert_id"), "exposure_assessments", ["alert_id"], unique=False
    )
    op.create_table(
        "verification_tasks",
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("admin_unit_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "SUBMITTED",
                "VERIFIED",
                "REJECTED",
                "MORE_EVIDENCE",
                name="verificationstatus",
            ),
            nullable=False,
        ),
        sa.Column("form_schema", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_unit_id"],
            ["admin_units.id"],
            name=op.f("fk_verification_tasks_admin_unit_id_admin_units"),
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"], ["alerts.id"], name=op.f("fk_verification_tasks_alert_id_alerts")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"], ["users.id"], name=op.f("fk_verification_tasks_assigned_to_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_tasks")),
    )
    op.create_index(
        op.f("ix_verification_tasks_alert_id"), "verification_tasks", ["alert_id"], unique=False
    )
    op.create_table(
        "action_items",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("owner_organization_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "ASSIGNED",
                "IN_PROGRESS",
                "BLOCKED",
                "COMPLETED",
                "CANCELLED",
                name="actionstatus",
            ),
            nullable=False,
        ),
        sa.Column("blockers", sa.JSON(), nullable=False),
        sa.Column("evidence_objects", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_action_items_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["owner_organization_id"],
            ["organizations.id"],
            name=op.f("fk_action_items_owner_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["action_plans.id"], name=op.f("fk_action_items_plan_id_action_plans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_items")),
    )
    op.create_index(op.f("ix_action_items_plan_id"), "action_items", ["plan_id"], unique=False)
    op.create_table(
        "field_reports",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("reporter_id", sa.Uuid(), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("evidence_objects", sa.JSON(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"], ["users.id"], name=op.f("fk_field_reports_reporter_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["verification_tasks.id"],
            name=op.f("fk_field_reports_task_id_verification_tasks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_reports")),
    )
    op.create_index(op.f("ix_field_reports_task_id"), "field_reports", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_field_reports_task_id"), table_name="field_reports")
    op.drop_table("field_reports")
    op.drop_index(op.f("ix_action_items_plan_id"), table_name="action_items")
    op.drop_table("action_items")
    op.drop_index(op.f("ix_verification_tasks_alert_id"), table_name="verification_tasks")
    op.drop_table("verification_tasks")
    op.drop_index(op.f("ix_exposure_assessments_alert_id"), table_name="exposure_assessments")
    op.drop_table("exposure_assessments")
    op.drop_index(op.f("ix_action_plans_alert_id"), table_name="action_plans")
    op.drop_table("action_plans")
    op.drop_table("playbooks")
    op.drop_table("notification_deliveries")
    # ### end Alembic commands ###
