"""observation_value_kind"""

import sqlalchemy as sa

from alembic import op

revision = "1724017f8ab2"
down_revision = "de04cc2e0ec6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("observations", sa.Column("value_kind", sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("observations", "value_kind")
    # ### end Alembic commands ###
