"""ml_registry_outcomes_scenarios"""

import sqlalchemy as sa

from alembic import op

revision = "cd34154a4eeb"
down_revision = "0a3008a0d26f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_snapshots",
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("target_definition", sa.JSON(), nullable=False),
        sa.Column("source_versions", sa.JSON(), nullable=False),
        sa.Column("object_uri", sa.String(length=1024), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_snapshots")),
        sa.UniqueConstraint("content_hash", name=op.f("uq_dataset_snapshots_content_hash")),
    )
    op.create_table(
        "feature_versions",
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("definitions", sa.JSON(), nullable=False),
        sa.Column("leakage_controls", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_versions")),
        sa.UniqueConstraint("version", name=op.f("uq_feature_versions_version")),
    )
    op.create_table(
        "model_versions",
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("dataset_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("feature_version_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_uri", sa.String(length=1024), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("model_card", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_snapshot_id"],
            ["dataset_snapshots.id"],
            name=op.f("fk_model_versions_dataset_snapshot_id_dataset_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["feature_version_id"],
            ["feature_versions.id"],
            name=op.f("fk_model_versions_feature_version_id_feature_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
        sa.UniqueConstraint("version", name=op.f("uq_model_versions_version")),
    )
    op.create_index(op.f("ix_model_versions_state"), "model_versions", ["state"], unique=False)
    op.create_table(
        "scenarios",
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("baseline_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("modifications", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("label", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["baseline_snapshot_id"],
            ["dataset_snapshots.id"],
            name=op.f("fk_scenarios_baseline_snapshot_id_dataset_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_scenarios_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenarios")),
    )
    op.create_table(
        "predictions",
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("admin_unit_id", sa.Uuid(), nullable=False),
        sa.Column(
            "domain",
            sa.Enum("DROUGHT", "RIVER_FLOOD", "FLASH_FLOOD", "FOOD_SECURITY", name="riskdomain"),
            nullable=False,
        ),
        sa.Column("target_period", sa.String(length=80), nullable=False),
        sa.Column("forecast_horizon_days", sa.Integer(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("NORMAL", "WATCH", "WARNING", "CRITICAL", name="risklevel"),
            nullable=False,
        ),
        sa.Column("uncertainty", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.JSON(), nullable=False),
        sa.Column("dataset_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("feature_version_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_unit_id"],
            ["admin_units.id"],
            name=op.f("fk_predictions_admin_unit_id_admin_units"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_snapshot_id"],
            ["dataset_snapshots.id"],
            name=op.f("fk_predictions_dataset_snapshot_id_dataset_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["feature_version_id"],
            ["feature_versions.id"],
            name=op.f("fk_predictions_feature_version_id_feature_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_predictions_model_version_id_model_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
    )
    op.create_index(
        op.f("ix_predictions_model_version_id"), "predictions", ["model_version_id"], unique=False
    )
    op.create_table(
        "outcomes",
        sa.Column("prediction_id", sa.Uuid(), nullable=False),
        sa.Column("observed", sa.Boolean(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_lineage", sa.JSON(), nullable=False),
        sa.Column("analyst_override", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.id"],
            name=op.f("fk_outcomes_prediction_id_predictions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outcomes")),
        sa.UniqueConstraint("prediction_id", name=op.f("uq_outcomes_prediction_id")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outcomes")
    op.drop_index(op.f("ix_predictions_model_version_id"), table_name="predictions")
    op.drop_table("predictions")
    op.drop_table("scenarios")
    op.drop_index(op.f("ix_model_versions_state"), table_name="model_versions")
    op.drop_table("model_versions")
    op.drop_table("feature_versions")
    op.drop_table("dataset_snapshots")
    # ### end Alembic commands ###
