"""data_source_governance_metadata"""

import sqlalchemy as sa

from alembic import op

revision = "de04cc2e0ec6"
down_revision = "cd34154a4eeb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data_sources", sa.Column("owner", sa.String(length=180), nullable=True))
    op.add_column("data_sources", sa.Column("terms_url", sa.String(length=1024), nullable=True))
    op.add_column(
        "data_sources", sa.Column("expected_frequency_minutes", sa.Integer(), nullable=True)
    )
    op.add_column(
        "data_sources", sa.Column("geographic_resolution", sa.String(length=120), nullable=True)
    )
    op.add_column("data_sources", sa.Column("historical_start", sa.Date(), nullable=True))
    op.add_column("data_sources", sa.Column("schedule", sa.String(length=120), nullable=True))
    op.add_column("data_sources", sa.Column("enabled", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_sources", "enabled")
    op.drop_column("data_sources", "schedule")
    op.drop_column("data_sources", "historical_start")
    op.drop_column("data_sources", "geographic_resolution")
    op.drop_column("data_sources", "expected_frequency_minutes")
    op.drop_column("data_sources", "terms_url")
    op.drop_column("data_sources", "owner")
    # ### end Alembic commands ###
