"""core_governance_entities"""

import sqlalchemy as sa

from alembic import op

revision = "f33ed614241c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_units",
        sa.Column("stable_code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("boundary_version", sa.String(length=80), nullable=False),
        sa.Column("boundary_source", sa.String(length=255), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["admin_units.id"], name=op.f("fk_admin_units_parent_id_admin_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_units")),
        sa.UniqueConstraint("stable_code", name=op.f("uq_admin_units_stable_code")),
    )
    op.create_table(
        "data_sources",
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("domain", sa.String(length=80), nullable=False),
        sa.Column("license", sa.String(length=255), nullable=True),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column("access_method", sa.String(length=50), nullable=False),
        sa.Column(
            "classification",
            sa.Enum("INTERNAL", "PARTNER", "PUBLIC", name="classification"),
            nullable=False,
        ),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
        sa.UniqueConstraint("name", name=op.f("uq_data_sources_name")),
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("organization_type", sa.String(length=80), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("name", name=op.f("uq_organizations_name")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=160), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_events_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_table(
        "observations",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_record_id", sa.String(length=255), nullable=False),
        sa.Column("admin_unit_id", sa.Uuid(), nullable=False),
        sa.Column("indicator_code", sa.String(length=120), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("reference_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "stage",
            sa.Enum("RAW", "VALIDATED", "NORMALIZED", "DERIVED", "PUBLISHED", name="datastage"),
            nullable=False,
        ),
        sa.Column("quality_flags", sa.JSON(), nullable=False),
        sa.Column("boundary_version", sa.String(length=80), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_unit_id"],
            ["admin_units.id"],
            name=op.f("fk_observations_admin_unit_id_admin_units"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["data_sources.id"], name=op.f("fk_observations_source_id_data_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observations")),
        sa.UniqueConstraint("source_id", "source_record_id", name="uq_observation_source_record"),
    )
    op.create_index(
        op.f("ix_observations_indicator_code"), "observations", ["indicator_code"], unique=False
    )
    op.create_table(
        "risk_signals",
        sa.Column(
            "domain",
            sa.Enum("DROUGHT", "RIVER_FLOOD", "FLASH_FLOOD", "FOOD_SECURITY", name="riskdomain"),
            nullable=False,
        ),
        sa.Column("admin_unit_id", sa.Uuid(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("NORMAL", "WATCH", "WARNING", "CRITICAL", name="risklevel"),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("drivers", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("target_period", sa.String(length=80), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_unit_id"],
            ["admin_units.id"],
            name=op.f("fk_risk_signals_admin_unit_id_admin_units"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_signals")),
    )
    op.create_index(op.f("ix_risk_signals_domain"), "risk_signals", ["domain"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("signal_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "IN_REVIEW",
                "VERIFICATION_REQUIRED",
                "VERIFIED",
                "APPROVED",
                "PUBLISHED",
                "RESOLVED",
                name="alertstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "classification",
            sa.Enum("INTERNAL", "PARTNER", "PUBLIC", name="classification"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_alerts_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"], ["risk_signals.id"], name=op.f("fk_alerts_signal_id_risk_signals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alerts")
    op.drop_index(op.f("ix_risk_signals_domain"), table_name="risk_signals")
    op.drop_table("risk_signals")
    op.drop_index(op.f("ix_observations_indicator_code"), table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("organizations")
    op.drop_table("data_sources")
    op.drop_table("admin_units")
    # ### end Alembic commands ###
